'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'fr' | 'en';

type Translations = Record<string, string>;

const translations: Record<Language, Translations> = {
  fr: {
    // Sidebar
    'nav.dashboard': "Vue d'ensemble",
    'nav.analytics': 'Analytique',
    'nav.crm': 'Clients',
    'nav.segments': 'Segments',
    'nav.products': 'Produits',
    'nav.categories': 'Catégories',
    'nav.orders': 'Commandes',
    'nav.whatsapp': 'WhatsApp',
    'nav.campaigns': 'Campagnes',
    'nav.finance': 'Finance',
    'nav.audit': 'Audit',
    'nav.admin': 'Administration',
    'nav.tenants': 'Boutiques',
    'sidebar.trial': "Version d'évaluation",
    'sidebar.monthly': 'Abonnement Mensuel',
    'sidebar.lifetime': 'Abonné à Vie',
    'sidebar.active': 'Boutique Active',
    'sidebar.lifetimeActive': 'Licence à vie active',
    'sidebar.upgradePro': 'Passer en Version Pro',
    'sidebar.upgradeLifetime': 'Passer à la Version à Vie',
    'sidebar.billing': 'Facturation',
    'sidebar.logout': 'Déconnexion',
    'sidebar.freemium': 'Plan Freemium',

    // Dashboard
    'dash.title': 'Tableau de Bord',
    'dash.subtitle': 'Pilotez l\'activité de votre commerce.',
    'dash.revenue': 'Chiffre d\'affaires',
    'dash.orders': 'Commandes',
    'dash.clients': 'Clients',
    'dash.pending_orders': 'Commandes en attente',
    'dash.recent_orders': 'Commandes récentes',
    'dash.vip_clients': 'Clients VIP',
    'dash.active_clients': 'Clients actifs',
    'dash.total_orders': 'Commandes totales',
    'dash.total_clients': 'Clients total',
    'dash.whatsapp_active': 'Canal WhatsApp actif',
    'dash.welcome_morning': 'Bonjour',
    'dash.welcome_afternoon': 'Bon après-midi',
    'dash.welcome_evening': 'Bonsoir',

    // Billing
    'bill.title': 'Abonnements & Facturation',
    'bill.subtitle': 'Choisissez la formule qui correspond à la taille de votre boutique.',
    'bill.monthly': 'Abonnement Mensuel',
    'bill.lifetime': 'Abonné à Vie',
    'bill.monthly_desc': 'Tous les outils essentiels pour votre commerce au mois le mois.',
    'bill.lifetime_desc': 'Payez une seule fois, profitez de BoutikFlow à vie.',
    'bill.features': 'Fonctionnalités incluses :',
    'bill.current': 'Votre plan actuel',
    'bill.choose': 'Choisir cette formule',
    'bill.orange_money': 'Paiement Orange Money',
    'bill.phone': 'Numéro de téléphone (Orange)',
    'bill.pay': 'Payer maintenant',
    'bill.cancel': 'Annuler',
    'bill.success': 'Paiement initié avec succès !',
    'bill.request_sent': 'Demande envoyée !',
    'bill.request_pro': 'Demander le passage en version PRO',
    'bill.request_desc': 'Pour activer la version, indiquez votre numéro de téléphone. L\'équipe BoutikFlow va vous contacter pour finaliser le changement.',
    'bill.phone_label': 'Votre numéro de téléphone',
    'bill.sending': 'Envoi en cours...',
    'bill.send_request': 'Envoyer la demande',

    // Products
    'prod.title': 'Catalogue Produits',
    'prod.subtitle': 'Gérez votre inventaire et vos prix.',
    'prod.add': 'Ajouter produit',
    'prod.search': 'Rechercher par nom, SKU ou code-barres...',
    'prod.name': 'Produit',
    'prod.category': 'Catégorie',
    'prod.price': 'Prix',
    'prod.stock': 'Stock',
    'prod.sku': 'SKU',
    'prod.status': 'Statut',
    'prod.actions': 'Actions',
    'prod.available': 'Disponible',
    'prod.unavailable': 'Indisponible',
    'prod.in_stock': 'en stock',
    'prod.out_of_stock': 'Rupture de stock',
    'prod.no_photo': 'Pas de photo',
    'prod.browse': 'Parcourir',
    'prod.ai_label': 'Photo du produit (Remplissage IA)',
    'prod.ai_analyzing': 'Analyse...',
    'prod.ai_prefill': "Auto-remplir par l'IA",
    'prod.name_label': 'Nom du produit *',
    'prod.sku_label': 'SKU (généré si vide)',
    'prod.barcode_label': 'Code-barres (facultatif)',
    'prod.price_label': 'Prix (GNF) *',
    'prod.stock_label': 'Stock *',
    'prod.category_select': 'Sélectionner une catégorie',
    'prod.description': 'Description',
    'prod.is_available': 'Produit disponible à la vente',
    'prod.new_product': 'Nouveau produit',
    'prod.edit_product': 'Modifier le produit',
    'prod.product_details': 'Détails du produit',
    'prod.confirm_delete': 'Confirmer la suppression',
    'prod.delete_msg': 'Êtes-vous sûr de vouloir supprimer ce produit ? Cette action est irréversible.',
    'prod.no_product': 'Aucun produit trouvé.',
    'prod.scan_camera': 'Scanner par caméra',

    // Orders
    'ord.title': 'Commandes',
    'ord.subtitle': 'Gérez vos commandes via le tunnel de vente (Kanban).',
    'ord.new': 'Nouvelle commande',
    'ord.export': 'Exporter',
    'ord.pending': 'En attente',
    'ord.confirmed': 'Confirmée',
    'ord.delivered': 'Livrée',
    'ord.cancelled': 'Annulée',
    'ord.articles': 'article(s)',
    'ord.details': 'Détails de la commande',
    'ord.client': 'Client',
    'ord.select_client': 'Sélectionner un client',
    'ord.items': 'Articles',
    'ord.scan_placeholder': 'Scanner un code-barres ou taper un SKU...',
    'ord.add_product': 'Ajouter un produit',
    'ord.notes': 'Notes (optionnel)',
    'ord.create': 'Créer la commande',
    'ord.creating': 'Création...',
    'ord.total': 'Montant total',
    'ord.created_at': 'Créée le',
    'ord.change_status': 'Changer le statut',
    'ord.current_status': 'Statut actuel :',
    'ord.move_to': 'Déplacer vers',
    'ord.confirm': 'Confirmer',
    'ord.updating': 'Mise à jour...',

    // CRM
    'crm.title': 'Clients (CRM)',
    'crm.subtitle': "Gérez vos clients et leur historique d'achat.",
    'crm.new': 'Nouveau client',
    'crm.search': 'Rechercher par nom ou numéro...',
    'crm.name': 'Client',
    'crm.phone': 'Téléphone',
    'crm.status': 'Statut',
    'crm.tags': 'Tags',
    'crm.last_activity': 'Dernière activité',
    'crm.no_client': 'Aucun client trouvé.',
    'crm.full_name': 'Nom complet *',
    'crm.phone_label': 'Téléphone *',
    'crm.email_label': 'Email (optionnel)',
    'crm.status_label': 'Statut',
    'crm.notes': 'Notes (optionnel)',
    'crm.new_status': 'Nouveau',
    'crm.active_status': 'Actif',
    'crm.vip_status': 'VIP',
    'crm.inactive_status': 'Inactif',
    'crm.details': 'Détails du client',
    'crm.edit': 'Modifier le client',
    'crm.confirm_delete': 'Confirmer la suppression',
    'crm.delete_msg': 'Êtes-vous sûr de vouloir supprimer ce client ? Cette action est irréversible.',

    // Campaigns
    'camp.title': 'Campagnes Marketing',
    'camp.subtitle': 'Créez, ciblez et suivez vos campagnes de diffusion par WhatsApp, SMS et E-mail.',
    'camp.new': 'Nouvelle campagne',
    'camp.search': 'Rechercher une campagne...',
    'camp.name': 'Nom de la campagne',
    'camp.channel': 'Canal',
    'camp.status': 'Statut',
    'camp.date': 'Date',
    'camp.sent': 'Envoyée',
    'camp.scheduled': 'Programmée',
    'camp.failed': 'Échouée',
    'camp.draft': 'Brouillon',
    'camp.no_campaign': 'Aucune campagne trouvée.',
    'camp.create': 'Créer une campagne',
    'camp.name_label': 'Nom de la campagne *',
    'camp.segment_label': 'Segment ciblé *',
    'camp.channel_label': 'Canal de diffusion *',
    'camp.message_label': 'Message *',
    'camp.schedule_label': 'Planification',
    'camp.save_draft': 'Enregistrer comme brouillon',
    'camp.send_now': 'Envoyer immédiatement',
    'camp.schedule_send': "Programmer l'envoi",
    'camp.schedule_date': "Date et Heure d'envoi *",
    'camp.create_send': 'Créer & Envoyer',
    'camp.confirm_delete': 'Confirmer la suppression',

    // WhatsApp
    'wa.title': 'WhatsApp Direct',
    'wa.subtitle': 'Rédigez vos messages et ouvrez WhatsApp directement — sans API, sans configuration.',
    'wa.tab_compose': 'Composer',
    'wa.tab_templates': 'Modèles rapides',
    'wa.tab_bulk': 'Envoi groupé',
    'wa.write_message': 'Rédiger le message',
    'wa.phone': 'Numéro de téléphone',
    'wa.message': 'Message',
    'wa.open_whatsapp': 'Ouvrir WhatsApp',
    'wa.preview': 'Aperçu du message',
    'wa.send_to_client': 'Envoyer à un client',
    'wa.search_client': 'Rechercher un client...',
    'wa.send': 'Envoyer',
    'wa.no_client': 'Aucun client trouvé. Ajoutez des clients depuis le module CRM.',
    'wa.use_template': 'Utiliser ce modèle',
    'wa.select_contacts': 'Sélectionner des contacts',
    'wa.campaign_message': 'Message de la campagne',
    'wa.send_all': 'Envoyer à tous',
    'wa.no_phone': 'Pas de numéro',

    // Analytics
    'ana.title': 'Analytique',
    'ana.subtitle': 'Performances de votre boutique.',
    'ana.loading': 'Chargement des analyses...',
    'ana.revenue': 'Revenu Total',
    'ana.orders': 'Commandes',
    'ana.avg_basket': 'Panier Moyen',
    'ana.delivery_rate': 'Taux de livraison',
    'ana.revenue_chart': 'Revenus',
    'ana.orders_chart': 'Commandes & Livraisons',
    'ana.delivered': 'Livrées',
    'ana.top_products': 'Top 5 Produits',
    'ana.client_segments': 'Répartition Clients',
    'ana.no_data': 'Aucune donnée pour cette période.',
    'ana.sales': 'vente(s)',

    // Segments
    'seg.title': 'Segments CRM',
    'seg.subtitle': 'Gérez les segments de votre clientèle pour vos campagnes marketing ciblées.',
    'seg.new': 'Créer un segment',
    'seg.total': 'Total Segments',
    'seg.search': 'Rechercher un segment...',
    'seg.name': 'Nom du segment',
    'seg.description': 'Description',
    'seg.filters': 'Filtres appliqués',
    'seg.members': 'Membres',
    'seg.no_segment': 'Aucun segment trouvé.',
    'seg.create': 'Créer un segment',
    'seg.name_label': 'Nom du segment *',
    'seg.desc_label': 'Description',
    'seg.status_label': 'Statut ciblé',
    'seg.all_statuses': 'Tous les statuts',
    'seg.tags_label': 'Tags requis (séparés par des virgules)',
    'seg.edit': 'Modifier le segment',
    'seg.confirm_delete': 'Confirmer la suppression',
    'seg.delete_msg': 'Êtes-vous sûr de vouloir supprimer ce segment ? Les clients associés ne seront pas supprimés.',

    // Categories
    'cat.title': 'Catégories de Produits',
    'cat.subtitle': 'Organisez votre catalogue pour la clientèle locale et internationale.',
    'cat.new': 'Nouvelle catégorie',
    'cat.search': 'Rechercher une catégorie...',
    'cat.view_products': 'Voir les produits →',
    'cat.no_category': 'Aucune catégorie trouvée.',
    'cat.name_label': 'Nom *',
    'cat.desc_label': 'Description',
    'cat.image_label': "URL de l'image (optionnel)",
    'cat.new_category': 'Nouvelle catégorie',
    'cat.edit': 'Modifier la catégorie',
    'cat.confirm_delete': 'Confirmer la suppression',
    'cat.delete_msg': 'Êtes-vous sûr de vouloir supprimer cette catégorie ? Les produits associés ne seront pas supprimés.',

    // Common
    'common.add': 'Ajouter',
    'common.edit': 'Modifier',
    'common.save': 'Enregistrer',
    'common.saving': 'Enregistrement...',
    'common.delete': 'Supprimer',
    'common.deleting': 'Suppression...',
    'common.cancel': 'Annuler',
    'common.close': 'Fermer',
    'common.loading': 'Chargement...',
    'common.yes': 'Oui',
    'common.no': 'Non',
    'common.actions': 'Actions',
    'common.created_at': 'Créé le',
    'common.name': 'Nom',
    'common.email': 'Email',
    'common.phone': 'Téléphone',
    'common.status': 'Statut',
    'common.clients': 'client(s)',
    'common.all_clients': 'Tous les clients',
    'common.download': 'Télécharger',
    'common.print': 'Imprimer',

    // Team
    'team.title': 'Gestion d\'Équipe',
    'team.subtitle': 'Gérez les membres et les rôles de votre boutique.',
    'team.invite': 'Inviter un membre',
    'team.name': 'Nom',
    'team.email': 'Email',
    'team.phone': 'Téléphone',
    'team.role': 'Rôle',
    'team.status': 'Statut',
    'team.active': 'Actif',
    'team.inactive': 'Inactif',
    'team.edit_role': 'Modifier le rôle',
    'team.confirm_delete': 'Confirmer la suppression',
    'team.delete_msg': 'Êtes-vous sûr de vouloir supprimer ce membre ?',
    'team.password': 'Mot de passe',
    'team.role_owner': 'Propriétaire',
    'team.role_manager': 'Gérant',
    'team.role_cashier': 'Caissier',
    'team.role_stock': 'Gestionnaire de stock',
    'team.role_staff': 'Employé',
    'team.error_fetch': 'Erreur lors de la récupération de l\'équipe',
    'team.invite_success': 'Membre invité avec succès',
    'team.error_invite': 'Erreur lors de l\'invitation',
    'team.status_updated': 'Statut mis à jour',

    // Suppliers
    'sup.title': 'Fournisseurs',
    'sup.subtitle': 'Gérez vos fournisseurs et approvisionnements.',
    'sup.new': 'Nouveau fournisseur',
    'sup.search': 'Rechercher un fournisseur...',
    'sup.name': 'Nom',
    'sup.company': 'Entreprise',
    'sup.phone': 'Téléphone',
    'sup.email': 'Email',
    'sup.city': 'Ville',
    'sup.country': 'Pays',
    'sup.contact': 'Personne de contact',
    'sup.address': 'Adresse',
    'sup.notes': 'Notes',
    'sup.no_supplier': 'Aucun fournisseur trouvé.',
    'sup.details': 'Détails du fournisseur',
    'sup.edit': 'Modifier le fournisseur',
    'sup.confirm_delete': 'Confirmer la suppression',
    'sup.delete_msg': 'Êtes-vous sûr de vouloir supprimer ce fournisseur ?',

    // Navigation
    'nav.pos': 'Caisse Rapide',
    'nav.suppliers': 'Fournisseurs',
    'nav.team': 'Équipe',
    'nav.management': 'Gestion',

    // Receipt
    'receipt.title': 'Reçu de vente',
    'receipt.print': 'Imprimer',
    'receipt.format': 'Format',
    'receipt.thermal': 'Thermique POS',
    'receipt.a4': 'Format A4',
    'receipt.number': 'Reçu N°',
    'receipt.date': 'Date',
    'receipt.seller': 'Vendeur',
    'receipt.client': 'Client',
    'receipt.product': 'Produit',
    'receipt.qty': 'Qté',
    'receipt.unit_price': 'P.U.',
    'receipt.subtotal': 'Sous-total',
    'receipt.total': 'TOTAL',
    'receipt.payment': 'Paiement',
    'receipt.cash': 'Espèces',
    'receipt.thanks': 'Merci pour votre achat !',
  },
  en: {
    // Sidebar
    'nav.dashboard': 'Overview',
    'nav.analytics': 'Analytics',
    'nav.crm': 'Customers',
    'nav.segments': 'Segments',
    'nav.products': 'Products',
    'nav.categories': 'Categories',
    'nav.orders': 'Orders',
    'nav.whatsapp': 'WhatsApp',
    'nav.campaigns': 'Campaigns',
    'nav.finance': 'Finance',
    'nav.audit': 'Audit',
    'nav.admin': 'Administration',
    'nav.tenants': 'Shops',
    'sidebar.trial': 'Trial Version',
    'sidebar.monthly': 'Monthly Subscription',
    'sidebar.lifetime': 'Lifetime Subscriber',
    'sidebar.active': 'Active Shop',
    'sidebar.lifetimeActive': 'Lifetime license active',
    'sidebar.upgradePro': 'Upgrade to Pro Version',
    'sidebar.upgradeLifetime': 'Upgrade to Lifetime',
    'sidebar.billing': 'Billing',
    'sidebar.logout': 'Log Out',
    'sidebar.freemium': 'Freemium Plan',

    // Dashboard
    'dash.title': 'Dashboard',
    'dash.subtitle': 'Manage your business activity.',
    'dash.revenue': 'Revenue',
    'dash.orders': 'Orders',
    'dash.clients': 'Customers',
    'dash.pending_orders': 'Pending Orders',
    'dash.recent_orders': 'Recent Orders',
    'dash.vip_clients': 'VIP Customers',
    'dash.active_clients': 'Active Customers',
    'dash.total_orders': 'Total Orders',
    'dash.total_clients': 'Total Customers',
    'dash.whatsapp_active': 'WhatsApp channel active',
    'dash.welcome_morning': 'Good morning',
    'dash.welcome_afternoon': 'Good afternoon',
    'dash.welcome_evening': 'Good evening',

    // Billing
    'bill.title': 'Subscriptions & Billing',
    'bill.subtitle': 'Choose the plan that matches your shop size.',
    'bill.monthly': 'Monthly Subscription',
    'bill.lifetime': 'Lifetime Subscriber',
    'bill.monthly_desc': 'All essential tools for your business on a month-to-month basis.',
    'bill.lifetime_desc': 'Pay once, enjoy BoutikFlow for a lifetime.',
    'bill.features': 'Included features:',
    'bill.current': 'Your current plan',
    'bill.choose': 'Choose this plan',
    'bill.orange_money': 'Orange Money Payment',
    'bill.phone': 'Phone number (Orange)',
    'bill.pay': 'Pay Now',
    'bill.cancel': 'Cancel',
    'bill.success': 'Payment initiated successfully!',
    'bill.request_sent': 'Request sent!',
    'bill.request_pro': 'Request PRO upgrade',
    'bill.request_desc': 'To activate the plan, enter your phone number. The BoutikFlow team will contact you to finalize the change.',
    'bill.phone_label': 'Your phone number',
    'bill.sending': 'Sending...',
    'bill.send_request': 'Send request',

    // Products
    'prod.title': 'Product Catalog',
    'prod.subtitle': 'Manage your inventory and prices.',
    'prod.add': 'Add product',
    'prod.search': 'Search by name, SKU or barcode...',
    'prod.name': 'Product',
    'prod.category': 'Category',
    'prod.price': 'Price',
    'prod.stock': 'Stock',
    'prod.sku': 'SKU',
    'prod.status': 'Status',
    'prod.actions': 'Actions',
    'prod.available': 'Available',
    'prod.unavailable': 'Unavailable',
    'prod.in_stock': 'in stock',
    'prod.out_of_stock': 'Out of stock',
    'prod.no_photo': 'No photo',
    'prod.browse': 'Browse',
    'prod.ai_label': 'Product photo (AI Fill)',
    'prod.ai_analyzing': 'Analyzing...',
    'prod.ai_prefill': 'Auto-fill with AI',
    'prod.name_label': 'Product name *',
    'prod.sku_label': 'SKU (auto-generated if empty)',
    'prod.barcode_label': 'Barcode (optional)',
    'prod.price_label': 'Price (GNF) *',
    'prod.stock_label': 'Stock *',
    'prod.category_select': 'Select a category',
    'prod.description': 'Description',
    'prod.is_available': 'Product available for sale',
    'prod.new_product': 'New product',
    'prod.edit_product': 'Edit product',
    'prod.product_details': 'Product details',
    'prod.confirm_delete': 'Confirm deletion',
    'prod.delete_msg': 'Are you sure you want to delete this product? This action is irreversible.',
    'prod.no_product': 'No products found.',
    'prod.scan_camera': 'Scan with camera',

    // Orders
    'ord.title': 'Orders',
    'ord.subtitle': 'Manage your orders through the sales pipeline (Kanban).',
    'ord.new': 'New order',
    'ord.export': 'Export',
    'ord.pending': 'Pending',
    'ord.confirmed': 'Confirmed',
    'ord.delivered': 'Delivered',
    'ord.cancelled': 'Cancelled',
    'ord.articles': 'item(s)',
    'ord.details': 'Order details',
    'ord.client': 'Customer',
    'ord.select_client': 'Select a customer',
    'ord.items': 'Items',
    'ord.scan_placeholder': 'Scan a barcode or type a SKU...',
    'ord.add_product': 'Add a product',
    'ord.notes': 'Notes (optional)',
    'ord.create': 'Create order',
    'ord.creating': 'Creating...',
    'ord.total': 'Total amount',
    'ord.created_at': 'Created on',
    'ord.change_status': 'Change status',
    'ord.current_status': 'Current status:',
    'ord.move_to': 'Move to',
    'ord.confirm': 'Confirm',
    'ord.updating': 'Updating...',

    // CRM
    'crm.title': 'Customers (CRM)',
    'crm.subtitle': 'Manage your customers and purchase history.',
    'crm.new': 'New customer',
    'crm.search': 'Search by name or number...',
    'crm.name': 'Customer',
    'crm.phone': 'Phone',
    'crm.status': 'Status',
    'crm.tags': 'Tags',
    'crm.last_activity': 'Last activity',
    'crm.no_client': 'No customers found.',
    'crm.full_name': 'Full name *',
    'crm.phone_label': 'Phone *',
    'crm.email_label': 'Email (optional)',
    'crm.status_label': 'Status',
    'crm.notes': 'Notes (optional)',
    'crm.new_status': 'New',
    'crm.active_status': 'Active',
    'crm.vip_status': 'VIP',
    'crm.inactive_status': 'Inactive',
    'crm.details': 'Customer details',
    'crm.edit': 'Edit customer',
    'crm.confirm_delete': 'Confirm deletion',
    'crm.delete_msg': 'Are you sure you want to delete this customer? This action is irreversible.',

    // Campaigns
    'camp.title': 'Marketing Campaigns',
    'camp.subtitle': 'Create, target and track your WhatsApp, SMS and Email campaigns.',
    'camp.new': 'New campaign',
    'camp.search': 'Search a campaign...',
    'camp.name': 'Campaign name',
    'camp.channel': 'Channel',
    'camp.status': 'Status',
    'camp.date': 'Date',
    'camp.sent': 'Sent',
    'camp.scheduled': 'Scheduled',
    'camp.failed': 'Failed',
    'camp.draft': 'Draft',
    'camp.no_campaign': 'No campaigns found.',
    'camp.create': 'Create a campaign',
    'camp.name_label': 'Campaign name *',
    'camp.segment_label': 'Target segment *',
    'camp.channel_label': 'Distribution channel *',
    'camp.message_label': 'Message *',
    'camp.schedule_label': 'Scheduling',
    'camp.save_draft': 'Save as draft',
    'camp.send_now': 'Send now',
    'camp.schedule_send': 'Schedule send',
    'camp.schedule_date': 'Send date & time *',
    'camp.create_send': 'Create & Send',
    'camp.confirm_delete': 'Confirm deletion',

    // WhatsApp
    'wa.title': 'WhatsApp Direct',
    'wa.subtitle': 'Write your messages and open WhatsApp directly — no API, no setup.',
    'wa.tab_compose': 'Compose',
    'wa.tab_templates': 'Quick templates',
    'wa.tab_bulk': 'Bulk send',
    'wa.write_message': 'Write message',
    'wa.phone': 'Phone number',
    'wa.message': 'Message',
    'wa.open_whatsapp': 'Open WhatsApp',
    'wa.preview': 'Message preview',
    'wa.send_to_client': 'Send to a customer',
    'wa.search_client': 'Search a customer...',
    'wa.send': 'Send',
    'wa.no_client': 'No customers found. Add customers from the CRM module.',
    'wa.use_template': 'Use this template',
    'wa.select_contacts': 'Select contacts',
    'wa.campaign_message': 'Campaign message',
    'wa.send_all': 'Send to all',
    'wa.no_phone': 'No number',

    // Analytics
    'ana.title': 'Analytics',
    'ana.subtitle': 'Your shop performance.',
    'ana.loading': 'Loading analytics...',
    'ana.revenue': 'Total Revenue',
    'ana.orders': 'Orders',
    'ana.avg_basket': 'Average Basket',
    'ana.delivery_rate': 'Delivery Rate',
    'ana.revenue_chart': 'Revenue',
    'ana.orders_chart': 'Orders & Deliveries',
    'ana.delivered': 'Delivered',
    'ana.top_products': 'Top 5 Products',
    'ana.client_segments': 'Customer Segments',
    'ana.no_data': 'No data for this period.',
    'ana.sales': 'sale(s)',

    // Segments
    'seg.title': 'CRM Segments',
    'seg.subtitle': 'Manage customer segments for targeted marketing campaigns.',
    'seg.new': 'Create segment',
    'seg.total': 'Total Segments',
    'seg.search': 'Search a segment...',
    'seg.name': 'Segment name',
    'seg.description': 'Description',
    'seg.filters': 'Applied filters',
    'seg.members': 'Members',
    'seg.no_segment': 'No segments found.',
    'seg.create': 'Create a segment',
    'seg.name_label': 'Segment name *',
    'seg.desc_label': 'Description',
    'seg.status_label': 'Target status',
    'seg.all_statuses': 'All statuses',
    'seg.tags_label': 'Required tags (comma-separated)',
    'seg.edit': 'Edit segment',
    'seg.confirm_delete': 'Confirm deletion',
    'seg.delete_msg': 'Are you sure you want to delete this segment? Associated customers will not be removed.',

    // Categories
    'cat.title': 'Product Categories',
    'cat.subtitle': 'Organize your catalog for local and international customers.',
    'cat.new': 'New category',
    'cat.search': 'Search a category...',
    'cat.view_products': 'View products →',
    'cat.no_category': 'No categories found.',
    'cat.name_label': 'Name *',
    'cat.desc_label': 'Description',
    'cat.image_label': 'Image URL (optional)',
    'cat.new_category': 'New category',
    'cat.edit': 'Edit category',
    'cat.confirm_delete': 'Confirm deletion',
    'cat.delete_msg': 'Are you sure you want to delete this category? Associated products will not be removed.',

    // Common
    'common.add': 'Add',
    'common.edit': 'Edit',
    'common.save': 'Save',
    'common.saving': 'Saving...',
    'common.delete': 'Delete',
    'common.deleting': 'Deleting...',
    'common.cancel': 'Cancel',
    'common.close': 'Close',
    'common.loading': 'Loading...',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.actions': 'Actions',
    'common.created_at': 'Created on',
    'common.name': 'Name',
    'common.email': 'Email',
    'common.phone': 'Phone',
    'common.status': 'Status',
    'common.clients': 'customer(s)',
    'common.all_clients': 'All customers',
    'common.download': 'Download',
    'common.print': 'Print',

    // Team
    'team.title': 'Team Management',
    'team.subtitle': 'Manage team members and roles for your shop.',
    'team.invite': 'Invite member',
    'team.name': 'Name',
    'team.email': 'Email',
    'team.phone': 'Phone',
    'team.role': 'Role',
    'team.status': 'Status',
    'team.active': 'Active',
    'team.inactive': 'Inactive',
    'team.edit_role': 'Edit role',
    'team.confirm_delete': 'Confirm deletion',
    'team.delete_msg': 'Are you sure you want to delete this member?',
    'team.password': 'Password',
    'team.role_owner': 'Owner',
    'team.role_manager': 'Manager',
    'team.role_cashier': 'Cashier',
    'team.role_stock': 'Stock Manager',
    'team.role_staff': 'Staff',
    'team.error_fetch': 'Error loading team',
    'team.invite_success': 'Member invited successfully',
    'team.error_invite': 'Error inviting member',
    'team.status_updated': 'Status updated',

    // Suppliers
    'sup.title': 'Suppliers',
    'sup.subtitle': 'Manage your suppliers and procurement.',
    'sup.new': 'New supplier',
    'sup.search': 'Search a supplier...',
    'sup.name': 'Name',
    'sup.company': 'Company',
    'sup.phone': 'Phone',
    'sup.email': 'Email',
    'sup.city': 'City',
    'sup.country': 'Country',
    'sup.contact': 'Contact person',
    'sup.address': 'Address',
    'sup.notes': 'Notes',
    'sup.no_supplier': 'No suppliers found.',
    'sup.details': 'Supplier details',
    'sup.edit': 'Edit supplier',
    'sup.confirm_delete': 'Confirm deletion',
    'sup.delete_msg': 'Are you sure you want to delete this supplier?',

    // Navigation
    'nav.pos': 'Quick Checkout',
    'nav.suppliers': 'Suppliers',
    'nav.team': 'Team',
    'nav.management': 'Management',

    // Receipt
    'receipt.title': 'Sales Receipt',
    'receipt.print': 'Print',
    'receipt.format': 'Format',
    'receipt.thermal': 'Thermal POS',
    'receipt.a4': 'A4 Format',
    'receipt.number': 'Receipt No.',
    'receipt.date': 'Date',
    'receipt.seller': 'Seller',
    'receipt.client': 'Customer',
    'receipt.product': 'Product',
    'receipt.qty': 'Qty',
    'receipt.unit_price': 'Unit Price',
    'receipt.subtotal': 'Subtotal',
    'receipt.total': 'TOTAL',
    'receipt.payment': 'Payment',
    'receipt.cash': 'Cash',
    'receipt.thanks': 'Thank you for your purchase!',
  }
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>('fr');

  useEffect(() => {
    const saved = localStorage.getItem('boutikflow_lang') as Language;
    if (saved === 'fr' || saved === 'en') {
      setLanguageState(saved);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('boutikflow_lang', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || translations['fr'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
