"""add tenant status and admin notifications

Revision ID: 763835cc1e8a
Revises: c5a91b3ef20d
Create Date: 2026-07-19 15:50:58.272924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '763835cc1e8a'
down_revision: Union[str, None] = 'c5a91b3ef20d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Postgres exige que le type ENUM existe avant d'être utilisé dans add_column
    # (contrairement à create_table qui le crée implicitement).
    tenant_status_enum = sa.Enum('pending', 'active', 'blocked', 'rejected', name='tenantstatusenum')
    tenant_status_enum.create(op.get_bind(), checkfirst=True)

    op.create_table('admin_notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('new_registration', name='adminnotificationtypeenum'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.String(length=2000), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(
        'tenants',
        sa.Column(
            'status',
            tenant_status_enum,
            nullable=False,
            server_default='pending',
        ),
    )
    # ### end Alembic commands ###

    # Préserver l'état des tenants existants : ceux déjà actifs restent actifs,
    # les autres passent en attente de validation.
    op.execute("UPDATE tenants SET status = 'active' WHERE is_active = TRUE")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'status')
    op.drop_table('admin_notifications')
    # ### end Alembic commands ###
    sa.Enum(name='tenantstatusenum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='adminnotificationtypeenum').drop(op.get_bind(), checkfirst=True)
